CREATE DATABASE IF NOT EXISTS coretech_cms CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE coretech_cms;

-- Admin users
CREATE TABLE usersCT (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Home page content
CREATE TABLE home_content (
  id INT PRIMARY KEY DEFAULT 1,
  hero_title VARCHAR(200) NOT NULL,
  hero_tagline VARCHAR(300) NOT NULL
);

CREATE TABLE sliders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  image_path VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- About page content
CREATE TABLE about_content (
  id INT PRIMARY KEY DEFAULT 1,
  mission TEXT NOT NULL,
  vision  TEXT NOT NULL
);

CREATE TABLE team (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  role VARCHAR(120) NOT NULL,
  photo_path VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Services (CRUD from www.coretechio.com structure you manage)
CREATE TABLE services (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Portfolio
CREATE TABLE portfolio (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  description TEXT,
  image_path VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Contact messages
CREATE TABLE messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL,
  subject VARCHAR(200),
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed single rows for settings tables
INSERT IGNORE INTO home_content (id, hero_title, hero_tagline)
VALUES (1, 'Innovate. Build. Scale.', 'CoreTech Innovations turns ideas into products.');

INSERT IGNORE INTO about_content (id, mission, vision)
VALUES (1, 'Our mission text...', 'Our vision text...');

-- Create default admin user (change password after first login!)
-- Replace 'admin123' hash with your own generated by PHP password_hash()
INSERT INTO usersCT (username, password_hash)
VALUES ('admin', '$2y$10$9T1S1sQmQW8nQbTz6O7k0uZK5Fmk7QpD3kE1pX2m2vZk7mZ9eY8yS');
